# packages in environment at /home/lobrien/anaconda3/envs/vqgan-clp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_pytorch_select           0.1                       cpu_0  
absl-py                   0.13.0                   pypi_0    pypi
aiohttp                   3.7.4.post0              pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               20.1.0           py37h27cfd23_1  
async-timeout             3.0.1                    pypi_0    pypi
async_generator           1.10             py37h28b3542_0  
attrs                     21.2.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
black                     21.4b2                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py37h27cfd23_1003  
ca-certificates           2021.7.5             h06a4308_1  
cachetools                4.2.2                    pypi_0    pypi
catalogue                 1.0.0                    py37_1  
certifi                   2021.5.30        py37h06a4308_0  
cffi                      1.14.5           py37h261ae71_0  
chardet                   4.0.0           py37h06a4308_1003  
click                     8.0.1                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cryptography              3.4.7            py37hd23ed53_0  
cycler                    0.10.0                   py37_0  
cymem                     2.0.5            py37h2531618_0  
cython                    0.29.24                  pypi_0    pypi
cython-blis               0.7.4            py37h27cfd23_1  
daal4py                   2021.2.2         py37ha9443f7_0  
dal                       2021.2.2           h06a4308_389  
dbus                      1.13.18              hb2f20db_0  
decorator                 5.0.9              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
detectron2                0.5                      pypi_0    pypi
einops                    0.3.0                    pypi_0    pypi
entrypoints               0.3                      py37_0  
expat                     2.4.1                h2531618_2  
fastcore                  1.3.20                     py_0    fastai
fastprogress              1.0.0              pyh39e3cac_0    fastai
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
fsspec                    2021.7.0                 pypi_0    pypi
ftfy                      6.0.3                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20210730          pypi_0    pypi
glib                      2.68.2               h36276a3_0  
google-auth               1.34.0                   pypi_0    pypi
google-auth-oauthlib      0.4.5                    pypi_0    pypi
grpcio                    1.39.0                   pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
hydra-core                1.1.0                    pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10               pyhd3eb1b0_0  
importlib-metadata        3.10.0           py37h06a4308_0  
importlib-resources       5.2.2                    pypi_0    pypi
importlib_metadata        3.10.0               hd3eb1b0_0  
intel-openmp              2019.4                      243  
iopath                    0.1.9                    pypi_0    pypi
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipympl                    0.7.0              pyhd3eb1b0_0  
ipython                   7.22.0           py37hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
jedi                      0.17.0                   py37_0  
jinja2                    3.0.0              pyhd3eb1b0_0  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.0.2                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py37h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kiwisolver                1.3.1            py37h2531618_0  
kornia                    0.5.8                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libmklml                  2019.0.5                      0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libuuid                   1.0.3                h1bed415_2  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.3                h2531618_0  
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py37h27cfd23_0  
matplotlib                3.3.4            py37h06a4308_0  
matplotlib-base           3.3.4            py37h62a2d02_0  
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.3.0            py37h54f3939_0  
mkl_random                1.1.1            py37h0573a6f_0  
mpi                       1.0                       mpich  
mpich                     3.3.2                hc856adb_0  
multidict                 5.1.0                    pypi_0    pypi
murmurhash                1.0.5            py37h2531618_0  
mypy-extensions           0.4.3                    pypi_0    pypi
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
nbstripout                0.5.0                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
ninja                     1.10.2               hff7bd54_1  
notebook                  6.4.0            py37h06a4308_0  
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46                     py37_0  
omegaconf                 2.1.0                    pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0  
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.4            py37h2531618_0  
pandoc                    2.12                 h06a4308_0  
pandocfilters             1.4.3            py37h06a4308_1  
parso                     0.8.2              pyhd3eb1b0_0  
pathspec                  0.9.0                    pypi_0    pypi
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.2.0            py37he98fc37_0  
pip                       21.1.2           py37h06a4308_0  
plac                      1.1.0                    py37_1  
portalocker               2.3.0                    pypi_0    pypi
preshed                   3.0.5            py37h2531618_4  
prometheus_client         0.11.0             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
prompt_toolkit            3.0.17               hd3eb1b0_0  
protobuf                  3.17.3                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.2                    pypi_0    pypi
pycparser                 2.20                       py_2  
pydeprecate               0.3.1                    pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pygments                  2.9.0              pyhd3eb1b0_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.17.3           py37h7b6447c_0  
pysocks                   1.7.1                    py37_1  
python                    3.7.10               h12debd9_4  
python-dateutil           2.8.1              pyhd3eb1b0_0  
pytorch-lightning         1.4.1                    pypi_0    pypi
pytz                      2021.1             pyhd3eb1b0_0  
pyyaml                    5.4.1            py37h27cfd23_1  
pyzmq                     20.0.0           py37h2531618_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.1                  h27cfd23_0  
regex                     2021.7.6                 pypi_0    pypi
requests                  2.25.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scikit-learn              0.24.2           py37ha9443f7_0  
scikit-learn-intelex      2021.2.2         py37h06a4308_0  
scipy                     1.6.2            py37h91f5cce_0  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py37h06a4308_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0           py37h06a4308_0  
spacy                     2.3.5            py37hff7bd54_0  
sqlite                    3.35.4               hdfb4753_0  
srsly                     1.0.5            py37h2531618_0  
tabulate                  0.8.9                    pypi_0    pypi
tbb                       2021.2.0             hff7bd54_0  
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4            py37h06a4308_0  
testpath                  0.4.4              pyhd3eb1b0_0  
thinc                     7.4.5            py37h9a67853_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                   pypi_0    pypi
torch                     1.8.1                    pypi_0    pypi
torchmetrics              0.4.1                    pypi_0    pypi
torchvision               0.9.1                    pypi_0    pypi
tornado                   6.1              py37h27cfd23_0  
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.3                    pypi_0    pypi
typing-extensions         3.7.4.3              hd3eb1b0_0  
typing_extensions         3.7.4.3            pyh06a4308_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
wasabi                    0.8.2              pyhd3eb1b0_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py37_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8                    pypi_0    pypi
yaml                      0.2.5                h7b6447c_0  
yarl                      1.6.3                    pypi_0    pypi
zeromq                    4.3.4                h2531618_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  
